name: eat
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pytorch=1.11.0 
  - torchvision=0.12.0
  - torchaudio
  - cudatoolkit=11.3
  - scikit-learn=0.24.2
  - matplotlib
  - scikit-image=0.17.2
  - librosa=0.8.1
  - pip
  - pip:
    - tensorflow-gpu==1.15.0
    - dlib==19.24.2
    - imageio==2.9.0
    - iou==0.1.0
    - munch==4.0.0
    - numpy
    - opencv_contrib_python==4.7.0.72
    - opencv_python==4.7.0.72
    - opencv_python_headless==4.7.0.68
    - Pillow
    - PyYAML==6.0.1
    - scipy
    - soundfile==0.12.1
    - tqdm==4.65.0
    - imageio-ffmpeg
    - pandas
    - resampy
    - python_speech_features
    - protobuf==3.20.0
    - imutils
