dataset_params:
  ###### CHANGE THE ROOT PATH HERE ######
  root_dir: /data2/gy/mead/images_evp_25/
  frame_shape: [256, 256, 3]
  id_sampling: False
  pairs_list: None
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: False
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1
  syncnet_T: 5


model_params:
  common_params:
    num_kp: 15 
    image_channel: 3                    
    feature_channel: 32
    estimate_jacobian: False
  kp_detector_params:
     temperature: 0.1
     block_expansion: 32            
     max_features: 1024
     scale_factor: 0.25
     num_blocks: 5
     reshape_channel: 16384  # 16384 = 1024 * 16
     reshape_depth: 16
  audio2kp_params:
     embedding_dim: 256
     num_kp: 15
     num_w: 5
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    reshape_channel: 32
    reshape_depth: 16         # 512 = 32 * 16
    num_resblocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 5
      # reshape_channel: 32
      reshape_depth: 16
      compress: 4
  discriminator_params:
    scales: [1]
    block_expansion: 32                 
    max_features: 512
    num_blocks: 4
    sn: True

train_params:
  num_epochs: 2000
  num_repeats: 1
  epoch_milestones: [180,]
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  lr_kp_detector: 2.0e-4
  lr_audio2kptransformer: 1.5e-4
  lr_emotionprompt: 2.0e-4
  lr_sidetuning: 2.0e-4
  gan_mode: 'hinge'    # hinge or ls
  batch_size: 4
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 1
  hopenet_snapshot: './checkpoints/hopenet_robust_alpha1.pkl'
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan: 0
    discriminator_gan: 0
    # feature_matching: [10, 10, 10, 10]
    feature_matching: [0, 0, 0, 0]
    # perceptual: [0, 0, 0, 0, 0]
    perceptual: [10, 10, 10, 10, 10]
    equivariance_value: 0
    equivariance_jacobian: 0
    keypoint: 0
    headpose: 0
    expression: 0
    latent: 100
    pca: 0
    dan: 0
    lmk: 0
    clip: 0
    img_l1: 10
    sync: 10
  train_with_img: True

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
